# Repository labels (stage gates)
# Sync with an action like crazy-max/ghaction-github-labeler
- name: stage/pillars
  color: "0366d6"
  description: "Stage gate — Pillars"
- name: stage/paths
  color: "0e8a16"
  description: "Stage gate — Learning Paths"
- name: stage/courses
  color: "fbca04"
  description: "Stage gate — Courses"
- name: stage/modules
  color: "7057ff"
  description: "Stage gate — Modules"
- name: stage/lessons
  color: "d93f0b"
  description: "Stage gate — Lessons"

# Audience labels (optional, for multi-segment items)
- name: role/analyst
  color: "c2e0c6"
  description: "Target role — Analyst"
- name: role/engineer
  color: "bfd4f2"
  description: "Target role — Engineer"
- name: role/manager
  color: "f9d0c4"
  description: "Target role — Manager"
- name: level/beginner
  color: "e6e6e6"
  description: "Target level — Beginner"
- name: level/intermediate
  color: "e0c5ff"
  description: "Target level — Intermediate"
- name: level/advanced
  color: "d4c5f9"
  description: "Target level — Advanced"
