# Adds issues and PRs to a GitHub Project (Projects v2)
# Setup required:
# 1) Create a user/org Project (Projects v2) and copy its URL
# 2) In this repo, set Repository Variable PROJECT_URL to that URL
# 3) Create a secret GH_PROJECT_TOKEN (classic PAT with project and repo scopes) if GITHUB_TOKEN lacks permission

name: Add to Project

on:
  issues:
    types: [opened, labeled, reopened]
  pull_request:
    types: [opened, labeled, reopened, ready_for_review]

jobs:
  add:
    if: ${{ vars.PROJECT_URL != '' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
