name: Add to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
      repository-projects: write
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.5.0
        with:
          # Note: Replace PROJECT_URL with your GitHub Project URL
          # Example: https://github.com/orgs/YOUR_ORG/projects/PROJECT_NUMBER
          # Or: https://github.com/users/YOUR_USER/projects/PROJECT_NUMBER
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          labeled: stage/pillars, stage/paths, stage/courses, stage/modules, stage/lessons
