name: Enforce stage label

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, reopened, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write
    steps:
      - name: Verify stage label present
        uses: actions/github-script@v7
        with:
          script: |
            const required = [
              'stage/pillars','stage/paths','stage/courses','stage/modules','stage/lessons'
            ];
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const ok = labels.some(l => required.includes(l));
            if (!ok) {
              core.setFailed('PR must include one stage label: ' + required.join(', '));
            }
