name: Stage Automation

on:
  pull_request:
    types:
      - labeled
      - unlabeled
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  update-project-status:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.label.name, 'stage/') ||
      (github.event.action == 'unlabeled' && contains(github.event.label.name, 'stage/'))
    permissions:
      issues: read
      pull-requests: read
    steps:
      - name: Update project item status
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.GH_PROJECT_TOKEN || secrets.GITHUB_TOKEN }}
          labeled: ${{ github.event.label.name }}
